language: node_js
node_js:
- '4.2'
deploy:
  provider: heroku
  api_key:
    secure: TaeapFe1fG7oIiYVBJXFym0loXRI/wyNNE+w3zdAQ1afqrSKIQIPQvDcNOweZQgFiLeBllQyRRmZxZyuv62f/JpeZ4Am7K9EliZghnhJuOhTcqJO3geEYdXbEN0rKpA1q5RJU0aOs03srGqZcJadSLzGwWt1VDgVAl5KcyEJbmD7v7aAYkOPQTfPQM2dfReLMP6S8lHAdm+iDN5kPN65qXbBuqa+0YmJKu9BWtUvDCCG84gTsQq2Osx/hA/RVhkpImSS9v5WXJNZ4qQCmyqF2IdGqW8QmaTeQvBhQz0oxfQ6ea8/y58zozrWcBiG3WC15f/VPQs7WIUEe8UqltzYo3kpX8tgkoFCALQwsJUtdpQDVvbmwf23iDOkyeMHYz9YBWkCcvT55NWeoWkA4E4FrOQbyWsXssrI3uphJjhtTw7L4rdKJHOaPHskOYGtp3TH0qTr9z/nHnKa0PjYH5yslAuUmTsLn7shFVKsaqu4QTUdlQWJ5a2GQpe/mvC1qjXiga0r341EYG6cZi2Zc0c9qzqIemGYTfwaeVmfdElM6ilVKmZY0HhzS2j4Y2M9qH6aM26C3h50FKktqGmJ2TSPSla7ztnUjRIg0TR8pVliWCvaUvuc7G36m6kOfQ+nd6tI5M6TPrrZYCO9U3mzIPJRFr6ZhXG85F0m8dSmeEF9/to=
  app: fbp-diffbot
  on:
    repo: jonnor/fbp-diffbot
